name: Generate SemVer

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Semantic Version
        id: semantic-version
      - uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "/!:|BREAKING CHANGE:/"
          minor_pattern: "/feat(\\(.+\\))?:/"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          user_format_type: "csv"
          debug: false